raise Exception("I am exception")
